
# name: Bank Backend Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   Continues-Integration_build_and_push:
#     runs-on: ubuntu-latest
#     env:
#       AWS_REGION: us-east-1

#     steps:
#     - name: Checkout backend repository
#       uses: actions/checkout@v3

#     - name: Configure AWS Credentials
#       uses: aws-actions/configure-aws-credentials@v3
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}

#     - name: Build Docker Image
#       run: docker build -t bank-app-backend:${{ github.run_number }} .

#     - name: Login to ECR
#       run: |
#         aws ecr get-login-password --region ${{ env.AWS_REGION }} \
#         | docker login --username AWS --password-stdin ${{ vars.ECR_REPO }}

#     - name: Tag Image
#       run: docker tag bank-app-backend:${{ github.run_number }} \
#            ${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}

#     - name: Push Image to ECR
#       run: docker push ${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}

#     - name: Cleanup Docker Images
#       run: |
#         docker rmi bank-app-backend:${{ github.run_number }} || true
#         docker rmi ${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }} || true


#   Continues-Update_k8s_manifest:
#     runs-on: ubuntu-latest
#     needs: Continues-Integration_build_and_push

#     steps:
#     - name: Clone Kubernetes manifest repo
#       env:
#         GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
#         GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
#       run: |
#         git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/floratech01/Bank-app-Kubernetes-manifest.git
#         cd Bank-app-Kubernetes-manifest

#         git config user.email "obianujuflorence02@gmail.com"
#         git config user.name "obianuju"

#         # Update backend image
#         sed -i "s+${{ vars.ECR_REPO }}/bank-backendapi:.*+${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}+g" \
#           bank-project/backendapi.yaml

#         # Ensure update succeeded
#         grep "${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}" bank-project/backendapi.yaml

#         # Commit and push changes
#         git add bank-project/backendapi.yaml
#         git commit -m "Update backendapi image to version ${{ github.run_number }}"
#         git push origin main




name: Bank Backend Pipeline.

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - cicd

jobs:
  Continues-Integration_build_and_push:
    runs-on: ubuntu
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: floratech01/bank-app-backend
        ref: main


    - name: Log in to awscli
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1


    - name: Build container image
      run: docker build -t bank-app-backend:${{ github.run_number }} .

    - name: Log in to ECR with short-lived credentials
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_REPO }}
  
    - name: Tag Docker image
      run: docker tag bank-app-backend:${{ github.run_number }} ${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}
    
    - name: Push image to ECR
      run: docker push ${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}


    - name: Clean up Docker image locally
      run: |
        docker rmi bank-app-backend:${{ github.run_number }}
        docker rmi ${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}

    - name: Clean up GitHub repo on runner
      run: rm -rf ./*


  
  Continues-Update_k8s_manifest:
    runs-on: ubuntu
    needs: Continues-Integration_build_and_push
    steps:
    - name: Checkout repository
      env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      run: |
         git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/floratech01/Bank-app-Kubernetes-manifest.git
         
         cd Bank-app-Kubernetes-manifest
         git config --global user.email "obianujuflorence02@gmail.com"
         git config --global user.name "obianuju"

         sed -i "s+${{ vars.ECR_REPO }}/bank-backendapi:.*+${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}+g" ./bank-project/backendapi.yaml

         cat ./bank-project/backendapi.yaml | grep -q "${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}"

         git add bank-project/backendapi.yaml
         git commit -m "Update. backendapi image to version ${{ github.run_number }}"
         git push origin main
        
