
name: Bank Backend Pipeline.

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - cicd

jobs:
  Continues-Integration_build_and_push:
    runs-on: ubuntu
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-north-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: CloudTitans-POD12/main_bank_app_backend
        ref: main


    - name: Log in to awscli
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1


    - name: Build container image
      run: docker build -t bank-app-backend:${{ github.run_number }} .

    - name: Log in to ECR with short-lived credentials
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ vars.ECR_REPO }}
  
    - name: Tag Docker image
      run: docker tag bank-app-backend:${{ github.run_number }} ${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}
    
    - name: Push image to ECR
      run: docker push ${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}


    - name: Clean up Docker image locally
      run: |
        docker rmi bank-app-backend:${{ github.run_number }}
        docker rmi ${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}

    - name: Clean up GitHub repo on runner
      run: rm -rf ./*


  
  Continues-Update_k8s_manifest:
    runs-on: ubuntu
    needs: Continues-Integration_build_and_push
    steps:
    - name: Checkout repository
      env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      run: |
         git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/digitalwitchdemo/kubernetes-manifest.git
         
         cd kubernetes-manifest
         git config --global user.email "janeanyanwu668@gmail.com"
         git config --global user.name "jayneAnya"

         sed -i "s+${{ vars.ECR_REPO }}/bank-backendapi:.*+${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}+g" ./bank-project/backendapi.yaml

         cat ./bank-project/backendapi.yaml | grep -q "${{ vars.ECR_REPO }}/bank-backendapi:${{ github.run_number }}"

         git add bank-project/backendapi.yaml
         git commit -m "Update. backendapi image to version ${{ github.run_number }}"
         git push origin main
        
